name: NX monorepo CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      # - run: npx nx format:check --base=origin/main
      # - run: npx nx affected -t lint --parallel=3 --base=origin/main
      # - run: npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage --coverageReporters=json,json-summary
      # - run: npx nx affected -t build --parallel=3 --base=origin/main

      - run: 'git branch --track ${{github.base_ref}} origin/${{github.base_ref}}'
      - run: 'git branch --track ${{github.head_ref}} origin/${{github.head_ref}}'
      - run: npx nx format:check --base=${{ github.base_ref }} --head=${{ github.head_ref }}
      - run: npx nx affected:lint --base=${{ github.base_ref }} --head=${{ github.head_ref }}
      - run: npx nx affected:test --base=${{  github.base_ref }} --head=${{ github.head_ref }} --configuration=ci
      - run: npx nx affected:build --base=${{  github.base_ref }} --head=${{ github.head_ref }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: dist/storybook/app1
          build_command: npx nx run app1:build-storybook
