name: NX monorepo CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check --base=origin/main
      - run: npx nx affected -t lint --parallel=3 --base=origin/main
      - run: npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage --coverageReporters=json,json-summary
      - run: npx nx affected -t build --parallel=3 --base=origin/main

      - name: Download Artifact (base code coverage results)
        uses: dawidd6/action-download-artifact@v2
        id: restoreCodeCoverage
        with:
          workflow: main-push.yaml
          workflow_conclusion: success
          branch: main
          name: code-coverage-report
          path: ./coverage-base
        continue-on-error: true

      - name: Comment Code Coverage on PR
        uses: dkhunt27/nx-code-coverage@v0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-folder: ./coverage
          coverage-base-folder: ./coverage-base
          gist-token: ${{ secrets.COVERAGE_BADGES_GIST_TOKEN }}
          gist-id: d7e6b443a01eba615fd2a7c1215aec91
          color: green
          named-logo: jest

      - name: Jest coverage reporter
        uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: 'npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage --coverageReporters=json,json-summary'
