name: NX monorepo CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx format:check --base=origin/main
      - run: npx nx affected -t lint --parallel=3 --base=origin/main
      - run: npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage --coverageReporters=json,json-summary
      - run: npx nx affected -t build --parallel=3 --base=origin/main

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage

      - name: TestCoverage
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false // defaults to false, if made true whole coverage report is commented with the diff
          runCommand: 'npx nx affected -t test --parallel=3 --configuration=ci --base=origin/main --coverage --coverageReporters=json,json-summary'
          delta: 0.5
